FROM node:18-alpine as deps
WORKDIR /app
COPY services/gateway/package.json services/gateway/tsconfig.json ./
RUN npm i --production=false
COPY services/gateway/src ./src
COPY shared ./shared
RUN npm run build

FROM node:18-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/dist ./dist
COPY --from=deps /app/shared ./shared
COPY services/gateway/package.json ./
RUN npm i --omit=dev
ENV GATEWAY_PORT=8080
EXPOSE 8080
CMD ["node","dist/index.js"]
