FROM node:18-alpine as deps
WORKDIR /app
COPY package.json ./
RUN npm i --production=false
COPY . .

# 👉 Tell the client bundle where Socket.IO lives
ENV NEXT_PUBLIC_GATEWAY_URL=http://localhost:8080
ENV NEXT_PUBLIC_GATEWAY_PATH=/socket.io

RUN npm run build

FROM node:18-alpine
WORKDIR /app
COPY --from=deps /app/.next ./.next
COPY --from=deps /app/package.json ./package.json
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/public ./public
EXPOSE 3000
CMD ["npm","start"]
